### ISSUE TITLE
Unable to add label

### ISSUE THREAD

**Issue by IamLucif3r** [anish-kmr/facelock#1]
I tried adding Label using 'facelock add myName', Camera gets opened however I was only able to see my face and nothing else was happening. I tried moving my face to different distances from camera as was mentioned however nothing happened.

**Comment by anish-kmr** [comment]
Is facelock detecting your face(a box will appear around your face if it is detected).
If yes, then press 'q' to quit camera and see if it is added to list by 'facelock list', then enable it by 'facelock enable'.
If not, then make sure that there is proper lights in the room and no flares are appearing on camera.

Let me know if that worked or not

**Comment by IamLucif3r** [comment]
Awesome ! It worked. Actually I was bit confused on Adding Label step. It was able to recognise my face but I didn't knew to press Q after it completes recognition. I think you should add this line in README. Also can we have option of default password lock screen if the user fails to get authenticated with the facelock ?

**Comment by anish-kmr** [comment]
Great! 
I forgot to add this point in README. Will update it.
And yes , if facelock fails to authenticate within 60 seconds , it asks for default password.
